import LayoutWrapper from "@/components/LayoutWrapper";

export const metadata = {
  title: "Ma3rood",
  description: "Generated by create next app",
};

export default function ProtectedLayout({ children }) {
  return (
       <LayoutWrapper>{children}</LayoutWrapper>
  );
}
